name: epat_2025_5nov
on: push

jobs:
  sync_scanning:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/maven@master
          env:
            SNYK_TOKEN: ${{ secrets.f4c18d27-29ab-4e91-8b36-b463a4ea1643 }}